name = "AdventOfCode2021"
uuid = "bb315b0d-18c1-466c-9a62-24d4bcc51bae"
authors = ["roflmaostc <fxw+git@mailbox.org>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "BenchmarkTools"]
